import base64
import hashlib
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
BUILDER = ROOT / "tools" / "build_pow_challenge.py"
MARKER = b"<!-- POW:PARAMS -->"
SCRIPT = b"void 0;\n"
VALID = (
    b"<!doctype html>\n"
    + MARKER
    + b"\n<script>"
    + SCRIPT
    + b"</script>\n"
)


class BuildPowChallengeTests(unittest.TestCase):
    def run_builder(self, source, existing=None):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        directory = Path(temporary.name)
        input_path = directory / "challenge.html"
        output_path = directory / "pow_challenge_page.h"

        input_path.write_bytes(source)
        if existing is not None:
            output_path.write_bytes(existing)

        result = subprocess.run(
            [sys.executable, str(BUILDER), str(input_path), str(output_path)],
            cwd=ROOT,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=5,
        )

        output = output_path.read_bytes() if output_path.exists() else None
        return result, output

    def array_bytes(self, header, name):
        pattern = (
            rb"static const u_char\s+"
            + name.encode("ascii")
            + rb"\[\]\s*=\s*\{(.*?)\};"
        )
        match = re.search(pattern, header, re.DOTALL)

        self.assertIsNotNone(match, name)
        values = re.findall(rb"0x([0-9a-f]{2})", match.group(1))
        return bytes(int(value, 16) for value in values)

    def test_emits_exact_template_bytes_and_script_digest(self):
        result, header = self.run_builder(VALID)

        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, b"")
        self.assertTrue(
            header.startswith(
                b"/*\n"
                b" * Generated by tools/build_pow_challenge.py.\n"
                b" * Do not edit manually.\n"
                b" */\n"
            )
        )

        prefix = self.array_bytes(header, "ngx_http_pow_challenge_prefix")
        suffix = self.array_bytes(header, "ngx_http_pow_challenge_suffix")
        digest = self.array_bytes(
            header, "ngx_http_pow_script_sha256_base64"
        )

        expected_prefix, expected_suffix = VALID.split(MARKER)
        self.assertEqual(prefix, expected_prefix)
        self.assertEqual(suffix, expected_suffix)
        self.assertEqual(prefix + suffix, VALID.replace(MARKER, b"", 1))
        self.assertEqual(
            digest,
            base64.b64encode(hashlib.sha256(SCRIPT).digest()),
        )
        self.assertEqual(len(digest), 44)
        self.assertTrue(digest.endswith(b"="))

    def test_emits_exact_checked_in_page_and_production_script_digest(self):
        source = (ROOT / "html" / "challenge.html").read_bytes()
        result, header = self.run_builder(source)

        self.assertEqual(result.returncode, 0, result.stderr)
        prefix = self.array_bytes(header, "ngx_http_pow_challenge_prefix")
        suffix = self.array_bytes(header, "ngx_http_pow_challenge_suffix")
        digest = self.array_bytes(
            header, "ngx_http_pow_script_sha256_base64"
        )
        expected_prefix, expected_suffix = source.split(MARKER)
        match = re.search(rb"<script>(.*?)</script>", source, re.DOTALL)

        self.assertIsNotNone(match)
        self.assertEqual(prefix, expected_prefix)
        self.assertEqual(suffix, expected_suffix)
        self.assertEqual(
            digest,
            base64.b64encode(hashlib.sha256(match.group(1)).digest()),
        )

    def test_accepts_structurally_valid_large_template(self):
        source = VALID + b"x" * ((15 * 1024) - len(VALID))
        result, header = self.run_builder(source)

        self.assertEqual(len(source), 15 * 1024)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIsNotNone(header)

    def test_output_is_deterministic(self):
        first_result, first = self.run_builder(VALID)
        second_result, second = self.run_builder(VALID)

        self.assertEqual(first_result.returncode, 0, first_result.stderr)
        self.assertEqual(second_result.returncode, 0, second_result.stderr)
        self.assertEqual(first, second)

    def test_rejects_invalid_templates_without_replacing_output(self):
        cases = {
            "empty": b"",
            "bom": b"\xef\xbb\xbf" + VALID,
            "nul": VALID + b"\x00",
            "invalid utf8": VALID + b"\xff",
            "no marker": VALID.replace(MARKER, b""),
            "two markers": VALID.replace(MARKER, MARKER + MARKER),
            "marker after script": VALID.replace(MARKER, b"") + MARKER,
            "marker inside script": VALID.replace(MARKER, b"").replace(
                SCRIPT, MARKER + SCRIPT
            ),
            "no script": MARKER,
            "two scripts": VALID + b"<script>x</script>",
            "uppercase script": VALID.replace(b"<script>", b"<SCRIPT>"),
            "spaced script": VALID.replace(b"<script>", b"<script >"),
            "attributed script": VALID.replace(
                b"<script>", b"<script src=\"x\">"
            ),
            "missing close": VALID.replace(b"</script>", b""),
            "empty script": VALID.replace(SCRIPT, b""),
        }

        for name, source in cases.items():
            with self.subTest(name=name):
                result, output = self.run_builder(source, b"keep\n")
                self.assertNotEqual(result.returncode, 0)
                self.assertEqual(result.stdout, b"")
                self.assertNotEqual(result.stderr, b"")
                self.assertLessEqual(len(result.stderr), 1024)
                self.assertEqual(output, b"keep\n")


if __name__ == "__main__":
    unittest.main()
