#!/usr/bin/env python3

import base64
import hashlib
import os
from pathlib import Path
import re
import sys
import tempfile


MARKER = b"<!-- POW:PARAMS -->"
SCRIPT_OPEN = b"<script>"
SCRIPT_CLOSE = b"</script>"
PAGE_LIMIT = 15 * 1024
WARNING = (
    b"/*\n"
    b" * Generated by tools/build_pow_challenge.py.\n"
    b" * Do not edit manually.\n"
    b" */\n"
)


def validate_template(data):
    if not data or len(data) >= PAGE_LIMIT:
        raise ValueError
    if data.startswith(b"\xef\xbb\xbf") or b"\x00" in data:
        raise ValueError

    data.decode("utf-8", errors="strict")

    if data.count(MARKER) != 1:
        raise ValueError

    openings = re.findall(br"<script(?:\s|>)", data, re.IGNORECASE)
    closings = re.findall(br"</script\s*>", data, re.IGNORECASE)
    if openings != [SCRIPT_OPEN] or closings != [SCRIPT_CLOSE]:
        raise ValueError

    open_at = data.find(SCRIPT_OPEN)
    close_at = data.find(SCRIPT_CLOSE, open_at + len(SCRIPT_OPEN))
    if open_at == -1 or close_at == -1:
        raise ValueError
    if data.find(MARKER) > open_at:
        raise ValueError

    script = data[open_at + len(SCRIPT_OPEN):close_at]
    if not script:
        raise ValueError

    prefix, suffix = data.split(MARKER)
    return prefix, suffix, script


def emit_array(name, data):
    lines = [f"static const u_char  {name}[] = {{\n"]

    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        encoded = ", ".join(f"0x{byte:02x}" for byte in chunk)
        comma = "," if offset + len(chunk) < len(data) else ""
        lines.append(f"    {encoded}{comma}\n")

    lines.append("};\n")
    lines.append(f"static const size_t  {name}_len = sizeof({name});\n\n")
    return "".join(lines).encode("ascii")


def build_header(data):
    prefix, suffix, script = validate_template(data)
    digest = base64.b64encode(hashlib.sha256(script).digest())

    output = bytearray(WARNING)
    output.extend(b"\n#ifndef NGX_HTTP_POW_CHALLENGE_PAGE_H\n")
    output.extend(b"#define NGX_HTTP_POW_CHALLENGE_PAGE_H\n\n\n")
    output.extend(emit_array("ngx_http_pow_challenge_prefix", prefix))
    output.extend(emit_array("ngx_http_pow_challenge_suffix", suffix))
    output.extend(
        emit_array("ngx_http_pow_script_sha256_base64", digest)
    )
    output.extend(b"#endif /* NGX_HTTP_POW_CHALLENGE_PAGE_H */\n")
    return bytes(output)


def atomic_write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )

    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main(argv):
    if len(argv) != 3:
        print("usage: build_pow_challenge.py INPUT OUTPUT", file=sys.stderr)
        return 2

    try:
        source = Path(argv[1]).read_bytes()
        header = build_header(source)
        atomic_write(Path(argv[2]), header)
    except (OSError, UnicodeError, ValueError):
        print("build_pow_challenge: invalid challenge template", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
